### ISSUE TITLE
Catalogazione dei tipi di errori di costuzione

### ISSUE THREAD

**Issue by GianlucaSog** [enriconardelli/Esecutore_SC_Eiffel#17]
In CONFIGURAZIONE l'attributo errore_costruzione è booleiano, se lo si trasforma in intero permette una più dettagliata descrizione del tipo di errore.

**Comment by enriconardelli** [comment]
Sì, sono d'accordo. Usiamo il valore 0 per "nessun errore", altri valori
positivi possono codificare le varie situazioni di errore. 

-- EN 

Il 2023-05-15 17:38 GianlucaSog ha scritto:

> In CONFIGURAZIONE l'attributo errore_costruzione è booleiano, se lo si trasforma in intero permette una più dettagliata descrizione del tipo di errore. 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- EN 

https://www.hoepli.it/libro/la-rivoluzione-informatica/9788896069516.html


 ====================================================== 
Prof. Enrico Nardelli 
Presidente di "Informatics Europe" 
Direttore del Laboratorio Nazionale "Informatica e Scuola" del CINI 
Dipartimento di Matematica - Università di Roma "Tor Vergata" 
Via della Ricerca Scientifica snc - 00133 Roma 
home page: https://www.mat.uniroma2.it/~nardelli 
blog: https://link-and-think.blogspot.it/ 
tel: +39 06 7259.4204 fax: +39 06 7259.4699 
mobile: +39 335 590.2331 e-mail: ***@***.*** 
online meeting: https://blue.meet.garr.it/b/enr-y7f-t0q-ont 
====================================================== 

-- 

Links:
------
[1] https://github.com/enriconardelli/Esecutore_SC_Eiffel/issues/17
[2]
